# Generated by Django 4.2.20 on 2025-06-10 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('testplans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('all', models.IntegerField(blank=True, default=0, help_text='用例总数', verbose_name='用例总数')),
                ('success', models.IntegerField(blank=True, default=0, help_text='用例成功', verbose_name='用例成功')),
                ('fail', models.IntegerField(blank=True, default=0, help_text='用例失败', verbose_name='用例失败')),
                ('error', models.IntegerField(blank=True, default=0, help_text='用例错误', verbose_name='用例错误')),
                ('pass_rate', models.CharField(blank=True, help_text='执行通过率', max_length=10, verbose_name='执行通过率')),
                ('tester', models.CharField(blank=True, help_text='测试人员', max_length=50, verbose_name='测试人员')),
                ('status', models.CharField(blank=True, help_text='执行状态', max_length=10, verbose_name='执行状态')),
                ('plan', models.ForeignKey(help_text='执行计划', on_delete=django.db.models.deletion.CASCADE, to='testplans.testplans', verbose_name='执行计划')),
                ('test_env', models.ForeignKey(blank=True, help_text='测试环境', max_length=50, on_delete=django.db.models.deletion.PROTECT, related_name='test_env', to='projects.testenv', verbose_name='测试环境')),
            ],
            options={
                'verbose_name': '用例执行记录表',
                'verbose_name_plural': '用例执行记录表',
                'db_table': 'tb_record',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('info', models.JSONField(blank=True, default=dict, help_text='测试报告', verbose_name='测试报告')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='reports.record')),
            ],
            options={
                'verbose_name': '用例报告表',
                'verbose_name_plural': '用例报告表',
                'db_table': 'tb_report',
            },
        ),
    ]
