# Generated by Django 4.2.20 on 2025-06-10 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('desc', models.TextField(blank=True, help_text='BUG描述', max_length=50000, verbose_name='BUG描述')),
                ('info', models.JSONField(blank=True, default=dict, help_text='测试报告', verbose_name='测试报告')),
                ('status', models.CharField(choices=[('未处理', '未处理'), ('已处理', '已处理'), ('无效BUG', '无效BUG'), ('处理中', '处理中')], default='未处理', help_text='BUG状态', max_length=10, verbose_name='BUG状态')),
                ('user', models.CharField(blank=True, default='', help_text='提交人员', max_length=50, verbose_name='提交人员')),
                ('interface', models.ForeignKey(help_text='接口', on_delete=django.db.models.deletion.CASCADE, to='projects.interface', verbose_name='接口')),
                ('project', models.ForeignKey(help_text='所属项目', on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'bug表',
                'verbose_name_plural': 'bug表',
                'db_table': 'tb_bug',
            },
        ),
        migrations.CreateModel(
            name='BugHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('handle', models.TextField(blank=True, help_text='处理操作', max_length=50000, verbose_name='处理操作')),
                ('update_user', models.CharField(blank=True, help_text='更新操作', max_length=50, verbose_name='更新人员')),
                ('bug', models.ForeignKey(help_text='bug ID', on_delete=django.db.models.deletion.CASCADE, to='bugs.bug', verbose_name='bug ID')),
            ],
            options={
                'verbose_name': 'bug处理记录表',
                'verbose_name_plural': 'bug处理记录表',
                'db_table': 'tb_bug_handle',
            },
        ),
    ]
