# Generated by Django 4.2.20 on 2025-06-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bughandle',
            name='reason',
            field=models.TextField(blank=True, help_text='处理原因', max_length=50000, verbose_name='处理原因'),
        ),
    ]
