# Generated by Django 4.2.20 on 2025-06-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_bughandle_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bughandle',
            options={'ordering': ['-created_time'], 'verbose_name': 'bug处理记录表', 'verbose_name_plural': 'bug处理记录表'},
        ),
        migrations.AddField(
            model_name='bughandle',
            name='status',
            field=models.CharField(choices=[('未处理', '未处理'), ('已处理', '已处理'), ('无效BUG', '无效BUG'), ('处理中', '处理中')], default='未处理', help_text='当前状态', max_length=10, verbose_name='当前状态'),
        ),
    ]
