# Generated by Django 4.2.20 on 2025-06-10 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='项目名称', max_length=50, verbose_name='项目名称')),
                ('leader', models.CharField(default='', help_text='项目负责人', max_length=50, verbose_name='项目负责人')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '项目表',
                'verbose_name_plural': '项目表',
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='TestEnv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='环境名称', max_length=150, verbose_name='环境名称')),
                ('globals_variables', models.JSONField(blank=True, default=dict, help_text='全局变量', null=True, verbose_name='全局变量')),
                ('debug_globals_variables', models.JSONField(blank=True, default=dict, help_text='debug模式全局变量', null=True, verbose_name='debug模式全局变量')),
                ('db', models.JSONField(blank=True, default=list, help_text='数据库配置', null=True, verbose_name='数据库配置')),
                ('host', models.CharField(blank=True, help_text='base_url地址', max_length=150, verbose_name='base_url地址')),
                ('headers', models.JSONField(blank=True, default=dict, help_text='请求头', null=True, verbose_name='请求头')),
                ('global_func', models.TextField(blank=True, default='# -*- coding: utf-8 -*-\n# @Time : 2025-4-25 11:18\n# @Author : wangxs1\n# @Email : wangxs1@xiaopeng.com\n# @File : global_func.py\n# @Software : PyCharm\n# @Project : Pugss\n# @bak :\n', help_text='测试工具文件', verbose_name='测试工具文件')),
                ('project', models.ForeignKey(help_text='项目id', on_delete=django.db.models.deletion.CASCADE, related_name='test_envs', to='projects.project', verbose_name='项目id')),
            ],
            options={
                'verbose_name': '测试环境表',
                'verbose_name_plural': '测试环境表',
                'db_table': 'tb_test_env',
            },
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='接口名称', max_length=150, verbose_name='接口名称')),
                ('url', models.CharField(help_text='接口地址', max_length=150, verbose_name='接口地址')),
                ('method', models.CharField(help_text='请求方法', max_length=10, verbose_name='请求方法')),
                ('type', models.CharField(choices=[('1', '项目接口'), ('2', '外部接口')], default='1', help_text='请求类型', max_length=40, verbose_name='请求类型')),
                ('project', models.ForeignKey(help_text='项目id', on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='projects.project', verbose_name='项目id')),
            ],
            options={
                'verbose_name': '接口表',
                'verbose_name_plural': '接口表',
                'db_table': 'tb_interface',
            },
        ),
    ]
